// Brand DTOs — the shared web/daemon contract for the Brands surface.
//
// A "brand" is a design system enriched with the parts that make styling into
// *branding*: an identity (name, tagline, logo), a measured design language
// (colors, typography), and a voice. Brands are extracted from a live URL by
// the daemon (deterministic prefetch → provisional preview → registered design
// system) and rendered by the web Brands library + detail pages.
//
// Pure TypeScript: no Node, browser, or daemon imports (contracts purity).

/** The seven semantic color roles every brand palette resolves to. */
export const BRAND_COLOR_ROLES = [
  'background',
  'surface',
  'foreground',
  'muted',
  'border',
  'accent',
  'accent-secondary',
] as const;
export type BrandColorRole = (typeof BRAND_COLOR_ROLES)[number];

export interface BrandColor {
  role: BrandColorRole;
  /** Lowercase #rrggbb. */
  hex: string;
  /** Optional oklch() string (filled by enrichment; empty in the provisional). */
  oklch: string;
  name: string;
  usage: string;
}

export interface BrandFontSpec {
  family: string;
  fallbacks: string[];
  weights: number[];
  /** Full Google Fonts stylesheet URL when the face is freely loadable. */
  googleFontsUrl?: string;
  notes?: string;
}

export interface BrandVoice {
  adjectives: string[];
  tone: string;
  messagingPillars: string[];
  vocabulary: { use: string[]; avoid: string[] };
}

/** A representative brand image harvested from the site (hero, product
 *  screenshot, illustration/photography sample, og:image). `file` is a path
 *  relative to the brand/project dir, e.g. "imagery/hero.png". */
export interface BrandImagerySample {
  file: string;
  /** Short category label, e.g. "hero", "product", "illustration". */
  kind?: string;
  /** One-line description shown under the thumbnail. */
  caption?: string;
}

export interface BrandImagery {
  style: string;
  subjects: string[];
  treatment: string;
  avoid: string[];
  /** Representative image samples saved under `imagery/`. Optional and
   *  backward-compatible: brands extracted before this field stay valid. */
  samples?: BrandImagerySample[];
}

export interface BrandLayout {
  radius: string;
  borderWeight: string;
  spacing: string;
  postureRules: string[];
}

/** The canonical brand kit — the single source of truth for every brand surface. */
export interface Brand {
  name: string;
  tagline: string;
  description: string;
  sourceUrl: string;
  logo: {
    /** Path relative to the brand dir, e.g. "logos/header-inline.svg". */
    primary: string | null;
    alternates: string[];
    notes: string;
  };
  colors: BrandColor[];
  typography: {
    display: BrandFontSpec;
    body: BrandFontSpec;
    mono?: BrandFontSpec;
  };
  voice: BrandVoice;
  imagery: BrandImagery;
  layout: BrandLayout;
}

/**
 * Brand lifecycle as surfaced to every brand UI.
 *   - `extracting`  : the backing extraction run is actively working.
 *   - `needs_input` : the backing run paused for the user (a question form /
 *     anti-bot wall). Reversible — flips back to `extracting` once the user
 *     answers, so it is derived on read and never persisted.
 *   - `ready`       : a brand kit was finalized + a design system registered.
 *   - `failed`      : the backing run failed or was canceled/stopped by the user.
 */
export type BrandStatus = 'extracting' | 'needs_input' | 'ready' | 'failed';

/** Server-written lifecycle record stored next to brand.json. */
export interface BrandMeta {
  id: string;
  sourceUrl: string;
  createdAt: number;
  updatedAt: number;
  status: BrandStatus;
  /** Human-readable failure reason when status === "failed". */
  error?: string;
  /** Backing extraction run that last drove this brand into a terminal failure. */
  extractionTerminalRunId?: string;
  /** Original terminal failure reason for that extraction run, preserved across daemon restarts. */
  extractionTerminalError?: string;
  /** The `user:<id>` design-system id this brand registered, so selecting the
   *  brand in the composer applies it through the existing design-system flow. */
  designSystemId?: string;
  /** Backing brand-generation project where extracted assets can be iterated. */
  projectId?: string;
  /** Files generated by the deterministic brand system builder. */
  systemFiles?: string[];
}

/** A brand as surfaced to the library list + detail page. */
export interface BrandSummary {
  meta: BrandMeta;
  brand: Brand | null;
}

export interface BrandListResponse {
  brands: BrandSummary[];
}

export interface BrandDetailResponse {
  meta: BrandMeta;
  brand: Brand | null;
  /** Prose brand guide markdown, when present. */
  guide: string | null;
}

/** POST /api/brands request — start an agent-driven brand extraction. */
export interface BrandCreateRequest {
  url: string;
}

/**
 * POST /api/brands response. Extraction is two-phase:
 *   1. PROGRAMMATIC-FIRST (synchronous): the daemon harvests the site
 *      deterministically (logo, palette, typography, one-line description,
 *      cover imagery, source URL), synthesizes a valid design system with NO
 *      LLM, and finalizes + registers it before responding — so the caller
 *      lands on a usable, applyable design system within seconds (the "aha").
 *   2. ASYNC AI ENRICHMENT: the backing `brand` project carries a seeded prompt
 *      the caller auto-sends; the agent re-measures precisely and re-finalizes
 *      in place (same `user:<id>` design system), updating every artifact.
 * A fully blocked / unreachable origin skips phase 1 and stays `extracting`
 * for the agent to drive — with a human in the loop for anti-bot walls.
 */
export interface BrandExtractStartResponse {
  /** The reserved brand id (status starts as `extracting`). */
  id: string;
  /** Backing `brand` project the agent runs the extraction inside. */
  projectId: string;
  /** Seeded conversation the first extraction prompt auto-sends into. */
  conversationId: string;
  /** The normalized source URL the browser tab was opened to. */
  sourceUrl: string;
}

/**
 * POST /api/brands/:id/finalize request. The extraction agent calls this (or
 * `od brand finalize`) once it has written `brand.json` (+ `BRAND.md`, logos,
 * fonts) into the backing project: the daemon validates the kit, derives the
 * design tokens + brand-system artifacts, and registers the `user:<id>` design
 * system so the brand becomes selectable everywhere.
 */
export interface BrandFinalizeRequest {
  /** Backing project whose `brand.json` holds the agent output. Defaults to
   *  the brand's recorded `projectId`. */
  projectId?: string;
}

export interface BrandFinalizeResponse {
  id: string;
  brand: Brand;
  designSystemId: string;
  projectId: string;
  /** Files emitted by the deterministic brand-system builder. */
  files: string[];
}

// ─── legacy extraction SSE events ────────────────────────────────────
//
// Retained for backwards compatibility with any external consumer that still
// reduces the old 3-stage SSE stream. The current extraction flow is
// agent-driven (see `BrandExtractStartResponse`) and does not emit these.

export type BrandExtractEvent =
  | { event: 'created'; id: string; projectId?: string }
  | { event: 'phase'; phase: 'prefetch' | 'preview' | 'system' | 'done' }
  | { event: 'prefetch'; step: string; detail?: string }
  | { event: 'prefetch-done'; colors: number; fonts: number; logos: number; thin: boolean }
  | { event: 'preview'; brand: Brand }
  | { event: 'system'; ok: boolean; designSystemId?: string; projectId?: string; files?: string[]; error?: string }
  | { event: 'brand'; id: string; brand: Brand; projectId?: string; designSystemId?: string; files?: string[] }
  | { event: 'error'; message: string };
